version: '3.1'
services:
  backend:
    image: ghcr.io/awlsring/terraform-backend-surreal:latest
    container_name: backend-surreal
    volumes:
      - ./config.yaml:/config/config.yaml
    ports:
      - 8032:8032
    restart: unless-stopped